server {
    listen 80;
    server_name _;

    root /var/www/windevs.uz/dist;
    index index.html;

    location = /health {
        add_header Content-Type text/plain;
        return 200 'ok';
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
